export const sneakersList =[
    "Nike Air Max 2023",
    "Adidas Ultraboost 21",
    "Puma RS-X3",
    "Reebok Classic Leather",
    "New Balance 990v4",
    "Asics Gel-Kayano 28",
    "Nike Air Force 1 '07",
    "Adidas Yeezy Boost 350 V2",
    "Converse Chuck Taylor All Star",
    "Vans Old Skool",
    "Under Armour HOVR Phantom",
    "Saucony Endorphin Speed",
    "Nike Zoom Pegasus 38",
    "Adidas NMD R1",
    "Puma Suede Classic",
    "Fila Disruptor 2",
    "New Balance Fresh Foam 1080v11",
    "Asics Gel-Nimbus 23",
    "Nike Air Zoom Terra Kiger 7",
    "Adidas Ultra Boost 20",
    "Puma Cali Sport",
    "Reebok Nano X1",
    "New Balance 574 Classic",
    "Nike React Element 55",
    "Adidas Superstar",
    "Asics Gel-Lyte III",
    "Vans Sk8-Hi",
    "Saucony Jazz Original",
    "Nike Air Max 97",
    "Adidas EQT Support 91/18",
    "Puma Future Rider",
    "Reebok Club C 85",
    "Nike Blazer Mid 77",
    "Adidas ZX 750",
    "Asics Gel-Saga",
    "New Balance 327",
    "Nike Air Max Plus",
    "Adidas Terrex Swift R2",
    "Puma Clyde Court",
    "Converse One Star",
    "Under Armour Curry One",
    "Reebok Classic Nylon",
    "Nike Air Max 90",
    "Adidas ZX Flux",
    "Vans Authentic",
    "Saucony Jazz 91",
    "Nike SB Dunk Low",
    "Adidas Prophere",
    "Puma RS-0 Sound",
    "Reebok InstaPump Fury",
    "New Balance 880v11",
    "Asics Gel-Kayano 26",
    "Nike Air Vapormax 2020",
    "Adidas Alphabounce",
    "Puma Basket Heart",
    "Reebok Freestyle Hi",
    "New Balance 1500",
    "Nike Free RN 5.0",
    "Adidas Nite Jogger",
    "Asics Gel-Venture 7",
    "Puma Disc Blaze",
    "Vans Era",
    "Saucony Endorphin Pro",
    "Nike Dunk Low",
    "Adidas Adizero Adios Pro",
    "Puma Thunder Spectra",
    "Reebok Zig Kinetica",
    "New Balance 1300",
    "Nike Air Zoom Freak 3",
    "Adidas Torsion X",
    "Puma LQDCELL Shatter",
    "Reebok Workout Plus",
    "Nike Air Max 720",
    "Adidas Continental 80",
    "Vans Old Skool Pro",
    "Saucony Triumph 18",
    "Nike Air Jordan 1",
    "Adidas Solar Glide 3",
    "Puma RS-2K",
    "Reebok Pump Omni Zone",
    "New Balance 1080v10",
    "Nike LeBron 18",
    "Adidas T-Mac Millennium",
    "Puma Future 5.1",
    "Reebok Ventilator",
    "Nike React Infinity Run",
    "Adidas Stan Smith",
    "Saucony Peregrine 11",
    "Puma Speed 500",
    "Reebok Speed TR",
    "New Balance 997H",
    "Nike Zoom Fly 3",
    "Adidas UltraBoost 21",
    "Puma Mirage Mox",
    "Reebok Royal Glide",
    "New Balance 880v9",
    "Nike Air Max 200",
    "Adidas UltraBoost 4.0",
    "Puma Speed Ignite Netfit",
    "Reebok Nano 9",
    "New Balance 860v11",
    "Nike Free RN Flyknit",
    "Adidas NMD XR1",
    "Puma Thunder Electric",
    "Reebok Club C Revenge",
    "New Balance 247",
    "Nike Air Zoom Pegasus 37",
    "Adidas NMD CS2",
    "Puma Clyde",
    "Reebok Runtone",
    "New Balance 5740",
    "Nike Air Huarache",
    "Adidas EQT Support ADV",
    "Puma Suede Classic XXI",
    "Reebok Classic Leather Legacy",
    "New Balance 991",
    "Nike Air Max 95",
    "Adidas Swift Run",
    "Puma RS-X Tracks",
    "Reebok Hexalite",
    "New Balance 990v3",
    "Nike Zoom Kobe 6",
    "Adidas Energy Boost 3",
    "Puma Future Rider Soul",
    "Reebok ZPrint Run",
    "New Balance 860v9",
    "Nike Zoom Air Fire",
    "Adidas Pureboost DPR",
    "Puma Velophasis",
    "Reebok Trial Runner",
    "New Balance 1010v1",
    "Nike Air Max 1",
    "Adidas Terrex AX3",
    "Puma Puma x Scuderia Ferrari",
    "Reebok CrossFit Nano 8",
    "New Balance 574 Sport",
    "Nike Blazer Low",
    "Adidas Gazelle",
    "Puma RS-Fast",
    "Reebok DMX Series 1200",
    "New Balance 860v10",
    "Nike Zoom Freak 2",
    "Adidas EQT 93/17",
    "Puma Thunder Desert",
    "Reebok Nano X2",
    "New Balance 880v12"
];